# SPDX-License-Identifier: Apache-2.0
name: Ubuntu Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Ubuntu
        run: ./scripts/setup-ubuntu.sh
      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
      - name: Format CMake files
        run: ./scripts/cmake-format.sh
      - name: Format code
        run: ./scripts/clang-format.sh
      - name: Clang-tidy Check
        run: ./scripts/clang-tidy.sh
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Ubuntu
        run: ./scripts/setup-ubuntu.sh
      - run: mkdir build
      - name: Run cmake
        run: cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: ninja -C build
      - name: Test
        run: ctest --test-dir build --output-on-failure
